phly/http

src/Uri.php
5.4 and earlier did not allow using the return value of a function call
inside `empty()`.
=> Ensure Uri class works under 5.4

src/Uri.php, test/UriTest.php
Paths can be empty. However, previously, a check for the first character not
being a slash always prepended a slash -- even when the path was empty.
This fixes phly/conduit#27
=> Allow empty paths

CHANGELOG.md, src/Uri.php, test/UriTest.php
Per #23 and #24, request-targets that represent either origin-form or absolute-form should never allow empty paths; an empty path is equivalent to the root path, "/".
=> Empty path == "/" for origin-form and absolute-form targets

README.md, test/ServerTest.php
With the change to Conduit's Next invokable, the callback to
`Server::listen()` needs to have the signature `function ($request,
$response, $error = null)` in order to be valid.
Interestingly, there was never a test for this functionality, though the
previous signature was documented.
=> Updated listen() to follow Conduit semantics

CHANGELOG.md, src/Request.php, test/RequestTest.php
When a new URI is present, the request target should be recalculated
(unless a request-target was explicitly set).
=> Ensure the request target gets recalculated

src/Uri.php, test/UriTest.php
In the current release using a numeric string for the Uri port throws an Exception. This fix checks correctly the Uri port in the method `withPort`
=> Fix the usage of numeric string Uri ports

src/Stream.php, test/StreamTest.php
Hey!
I'm currently integrating your library in egeloen/ivory-http-adapter#74 and I have noticed the `Stream::getSize` always return `null`. Is it intended?
=> [Stream] Determine stream size

src/Uri.php
Avoid rebuilding the uri string if the uri instance is used as (or casted to) string more than once.
=> cache generated uri string

src/MessageTrait.php, src/Request.php, src/RequestTrait.php, src/ServerRequest.php, test/RequestTest.php
When implementing PSR-7, I was creating a client that used the headers of a message to send a request. All of my requests were failing because there was no Host header, which made me realize that the Host header of a request was not being updated when a URI is given to a request. I made this change to make consumers of a message not need to also check the URI for a host but can rather just rely on the headers provided by the request.
The logic I settled on was that when a URI is set on a request (whether in the constructor or withUri()), the Host header is updated to the host of the URI if it is present. I am opening this issue just to let you know and see if you wanted to make a similar change.
=> Update host when URI is set?

src/Uri.php, test/UriTest.php
If this isn't already part of the spec, maybe it should be, but in my implementation, I'm percent encoding characters in the query, path, and fragment when they are set on a URI.
See: https://github.com/guzzle/psr7/blob/master/src/Uri.php#L491
(note: the regexes here are based on the regexes used in ZF2's URI filtering)
=> Filter query, path, and fragment in URIs?

src/Server.php
This change allows the `Server` class to be inherited and to return the child class instead of `Server` when calling `Server::createServerFromRequest`.
=> Replace self with static in Server.php to make use of late static bindings

src/Uri.php, test/UriTest.php
Changed parseUri() to filter the scheme so a Uri cannot be constructed with an invalid scheme. The list of schemes can be modified by an extending class if an implementation wanted to support additional schemes.
Also altered getPort() to return null if the port was set to the standard port for the scheme.
=> Updated Uri to validate scheme when constructed.

src/Uri.php
Steps to reproduce:
<?php
$uri = new Phly\Http\Uri('http://google.com/foo/bar');
serialize($uri);
=> Uri object can't be serialized #53

CHANGELOG.md, composer.json, src/MessageTrait.php, src/PhpInputStream.php, src/Request.php, src/RequestTrait.php, src/Response.php, src/ServerRequest.php, src/ServerRequestFactory.php, src/Stream.php, src/UploadedFile.php, src/Uri.php, test/MessageTraitTest.php, test/RequestTest.php, test/ServerRequestFactoryTest.php, test/ServerRequestTest.php, test/StreamTest.php, test/UploadedFileTest.php, test/UriTest.php
This pull request updates phly/http to the `0.10.*` version of the PSR-7 specification.
For a list of updates in that version, please [read my write-up](https://gistlog.co/weierophinney/8479b78e9ddcc9a16d9d).
In particular, this version:
- Adds `Phly\Http\UploadedFile`.
- Updates the various header retrieval methods in `Phly\Http\MessageTrait` to follow the new signatures.
- Updates `Phly\Http\Stream` to raise exceptions for error conditions.
- Updates `Phly\Http\ServerRequestFactory` to manipulate the `$_FILES` superglobal and normalize it to a tree of `UploadedFile` instances.
- Updates `Phly\Http\ServerRequest` to define `getUploadedFiles()` and `withUploadedFiles()`, and to remove `getFileParams()`.
- Adds the `$preserveHost` parameter to `Phly\Http\Uri`.
=> Update to psr/http-message 0.10

CHANGELOG.md, composer.json, src/Response.php, src/UploadedFile.php, test/ResponseTest.php, test/UploadedFileTest.php
We're finishing the second review of PSR-7; this patch syncs phly/http with the changes introduced during review. There were only two substantive changes:
- `UploadedFileInterface::move()` was renamed to `moveTo()`.
- The reason phrase in the `ResponseInterface` is now _always_ a string, even when undefined.
=> Sync phly/http with psr/http-message

src/HeaderSecurity.php, src/MessageTrait.php, src/RequestTrait.php, src/Response.php, test/HeaderSecurityTest.php, test/MessageTraitTest.php, test/RequestTest.php, test/ResponseTest.php
Zend Framework reported in [ZF2015-04](http://framework.zend.com/security/advisory/ZF2015-04) potential CRLF attack vectors in HTTP headers. This patch borrows code from ZF2 to protect against similar vectors in phly/http.
Introduced is a new class, `Phly\Http\HeaderSecurity`, with the following methods:
- `filter($value)`, which will filter a header value of any illegal characters or invalid continuation sequences.
- `isValid($value)`, which will indicate whether or not the value follows RFC 7230 specifications.
- `assertValid($value)`, which will raise an exception for an invalid value.
`MessageTrait` was updated to raise exceptions in the case of invalid header names or values being passed to `withHeader()` and `withAddedHeader()`. Both `RequestTrait::initialize()` and …
=> Ensure headers are not open to CRLF vectors

composer.json
Rationale: there are other implementations of this PSR. This allows developers to rely on an implementation of the PSR instead of a concrete package. Since this is considered to be the "first" implementation, it is a good place to start this practice.
=> Adds virtual package to composer

composer.json, composer.lock
Apparently upgrading PHPUnit to latest stable version is helpful for finding some problems :-)
It also comes with Prophecy, which is super-extra-cool for mocking, much easier (and readable) than default mocking engine, that can be leveraged in future PRs.
Note: test will start to pass once #71 is fixed.
=> Upgrade PHPUnit to v4.6

src/Server.php, test/ServerTest.php
Per #71 , several `Server` unit tests are marked "risky" due to the fact that the output buffer is not flushed completely. This patch does the following:
- Updates those tests to call `ob_end_flush()` after the call to `listen()`. This is necessary as the emitter flushes output only to the `ob_level` at the time it was called.
- Modifies `Server` to pass the current `ob_level` to the emitter, and removes the stateful property for tracking the level (it's no longer necessary).
=> Fix unit tests for Server to work under PHPUnit 4.6

test/StreamTest.php
`Stream::isSeekable` doesn't throw any exceptions, so it seems that this test is not needed at all.
=> Remove unneded test
